backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: "manuals" # Used in routes, e.g., /admin/collections/blog
    label: "Manuals" # Used in the UI
    folder: "content/manuals" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cover Image", name: "imagecovercatalog", widget: "string"}
      - {label: "Download id", name: "downloadid", widget: "string"}
      - {label: "Sendowl", name: "sendowlmd", widget: "string"}
      - {label: "Manual Price", name: "manualprice", widget: "string"}
      - {label: "ISBN", name: "isbn", widget: "string"}
      - {label: "SKU", name: "sku", widget: "string"}
      - {label: "TOC", name: "manualtoc", widget: "markdown"}
      - {label: "Cover", name: "manualcover", widget: "markdown"}
      - {label: "Manual Description", name: "manualdescription", widget: "markdown"}
      - {label: "Year", name: "manualyear", widget: "string"}
      - {label: "Make", name: "manual", widget: "string"}
      - {label: "pccon", name: "pccon", widget: "markdown"}
      - {label: "pcpro", name: "pcpro", widget: "markdown"}
      - {label: "Add to Cart", name: "partialaddtocart", widget: "markdown"}
      - {label: "Series", name: "series", widget: "string"}
      - {label: "Sub Series", name: "subseries", widget: "string"}
      - {label: "Platform", name: "platform", widget: "string"}
      - {label: "Body Type", name: "bodytype", widget: "string"}
      - {label: "Fuel Type", name: "fueltype", widget: "string"}
      - {label: "Data Item id", name: "dataitemid", widget: "string"}
      - {label: "Data Item name", name: "dataitemname", widget: "string"}
      - {label: "Data Item price", name: "dataitemprice", widget: "string"}
      - {label: "Data Item URL", name: "dataitemurl", widget: "string"}
      - {label: "Data Item Image", name: "dataitemimage", widget: "string"}
      - {label: "Data Item shipable", name: "dataitemshippable", widget: "string"}
      - {label: "Data Item taxable", name: "dataitemtaxable", widget: "string"}
      - {label: "Data Item fileguide", name: "dataitemfileguid", widget: "string"}
      - {label: "Data Item custom name", name: "dataitemcustomname", widget: "string"}
      - {label: "Data Item custom Option", name: "dataitemcustomoptions", widget: "string"}
      - {label: "Data Item custom Option", name: "dataitemcustomoptions", widget: "string"}
      - {label: "Image Cover Catlog", name: "imagecovercatalog", widget: "string"}
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "markdown"}
